# Generated by Django 4.1.2 on 2022-10-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('longitude', 'latitude')},
        ),
    ]
